version: '3.8'

services:
  chain-events-processing:
    container_name: chain-events-processing
    restart: always
    build:
      context: ../
      dockerfile: docker/app.Dockerfile
    env_file:
      - .env
    ports:
      - "5002:5002"
    networks:
      - rivada-net

networks:
  rivada-net:
    driver: bridge
